List<Map<String, dynamic>> users = [
  {
    'id': 1,
    'username': 'taona',
    "first_name": "taona",
    "last_name": "gooner",
    'password': 'test',
    'email_address': '3x9oJ@example.com',
    'phone_number': "0781830006",
    "city": "Mutare",
    'isAdmin': true,
    "isStaff": true,
    "isActive": true,
  },
  {
    'id': 2,
    'username': 'deon',
    'password': 'test',
    "first_name": "deon",
    "last_name": "smith",
    'email_address': '3x9oJ@example.com',
    'phone_number': "0781830006",
    "city": "Mutare",
    'isAdmin': false,
    "isStaff": true,
    "isActive": true,
  },
  {
    'id': 3,
    'username': 'benjamin',
    "first_name": "benjamin",
    "last_name": "frank",
    'password': 'test',
    'email_address': '3x9oJ@example.com',
    'phone_number': "0781830006",
    "city": "Mutare",
    'isAdmin': false,
    "isStaff": false,
    "isActive": true,
  },
];
